# Numpy Exercise  <img src = "numpy1.png">
###### Authored by T.K.Senthil Kumar

#### 1. Create a numpy array with the number of elements equals your age. The value of array elements is a random number between 10 to your age 

In [40]:
#Solution
import numpy as np
age=35
print('Age is : ',age)
ar1 = np.random.randint(10,age,age)
print('\n',ar1)
print('\nSize of array is :',ar1.size)


Age is :  35

 [23 33 30 31 17 34 22 17 17 33 21 21 29 32 15 17 17 16 31 16 17 18 13 22
 29 20 12 13 32 19 17 19 25 20 10]

Size of array is : 35


#### 2. Create a numpy array between 1 to 50 with the span(space) of 2 and print the length of the array

In [43]:
# Solution
ar2=np.arange(1,50,2) 
print('\n',ar2)
print('\nSize of array is :',ar2.size)



 [ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49]

Size of array is : 25


#### 3. Create an equally spaced numpy array with 27 elements between 4 and 7 

In [44]:
# Solution

ar3=np.linspace(4,7,num=27) 
print('\n',ar3)
print('\nSize of array is :',ar3.size)



 [4.         4.11538462 4.23076923 4.34615385 4.46153846 4.57692308
 4.69230769 4.80769231 4.92307692 5.03846154 5.15384615 5.26923077
 5.38461538 5.5        5.61538462 5.73076923 5.84615385 5.96153846
 6.07692308 6.19230769 6.30769231 6.42307692 6.53846154 6.65384615
 6.76923077 6.88461538 7.        ]

Size of array is : 27


#### 4. Create a matrix of size (5 x 4) with random numbers and round off the each elements by only 2 fractional points.

In [60]:
# Solution
ar4= np.random.rand(5,4)
ar4_r= np.around(ar4,2)

print('\n',ar4_r)
print('\nShape of array is :',ar4_r.shape)






 [[0.19 0.87 0.51 0.21]
 [0.65 0.62 0.01 0.62]
 [0.3  0.93 0.15 0.47]
 [0.05 0.46 0.72 0.69]
 [0.88 0.81 0.02 0.69]]

Shape of array is : (5, 4)


#### 5. Create a matrix of size (5x5) with random integers between 5 to 15

In [62]:
# Solution
ar5 = np.random.randint(5,15,(5,5))
print('\n',ar5)
print('\nSize of array is :',ar5.size)
print('\nShape of array is :',ar5.shape)




 [[10 11 13  7  8]
 [ 5 12  8  6 12]
 [13  5 10  6  6]
 [10  7  6  5 10]
 [11  9 11 11  8]]

Size of array is : 25

Shape of array is : (5, 5)


#### 6. Create the one dimensional array of zeros of random length below 20 with the data type int32

In [86]:
# Solution

ar6=np.zeros(np.random.randint(1,20),dtype='int32')
print(ar6)
print('\nSize of array is :',ar6.size)
print('\nType of array is :',ar6.dtype)




[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]

Size of array is : 17

Type of array is : int32


#### 7. Create a two dimensional array of ones of random row and column lengths with the data type of float32 

In [89]:
# Solution
ar7=np.ones((np.random.randint(1,4),np.random.randint(1,4)),dtype='float32')
print(ar7)
print('\nSize of array is :',ar7.size)
print('\nType of array is :',ar7.dtype)





[[1. 1. 1.]
 [1. 1. 1.]]

Size of array is : 6

Type of array is : float32


#### 8. Create a matrix exactly as same as shown below and print its shape, type and dtype
<img src = "np_mat1.png">

In [219]:
# Solution
ar  = np.array([9,25,50,34,45,3,34,34,65,2,5,7,3,76,3,7,8,6,54,6,23,12,8,5,8],dtype='i')
ar8 = ar.reshape(5,5)
print(ar8)
print('Array data type is :',ar8.dtype)
print('Array shape is     :',ar8.shape)

m1 = np.matrix(ar8)
print('m1 matrix type is  :',type(m1))
print('m1 matrix is  :',type(m1))



[[ 9 25 50 34 45]
 [ 3 34 34 65  2]
 [ 5  7  3 76  3]
 [ 7  8  6 54  6]
 [23 12  8  5  8]]
Array data type is : int32
Array shape is     : (5, 5)
m1 matrix type is  : <class 'numpy.matrix'>
m1 matrix is  : <class 'numpy.matrix'>


#### 9. Access the center pixel of the matrix defined in the question no 8 ( Don't enter the row and column index explicitely)

In [121]:
# Solution
print(m1)
m1_d = np.matrix.diagonal(m1) 
print('\nSize of diagonal array is:', m1_d.size)
m2_dc=int(np.round(m1_d.size/2))

print('\nMiddle pixel of Main array is : ',m1_d[0,m2_dc])


[[ 9 25 50 34 45]
 [ 3 34 34 65  2]
 [ 5  7  3 76  3]
 [ 7  8  6 54  6]
 [23 12  8  5  8]]

Size of diagonal array is: 5

Middle pixel of Main array is :  3


#### 10. Print the all the elements of 3rd row of the matrix

In [149]:
# Solution


print(m1[2])

        
    



[[ 5  7  3 76  3]]


#### 11. Print the all the elements of 4th columns of the matrix

In [153]:
# Solution
    
print(m1[:,3])


[[34]
 [65]
 [76]
 [54]
 [ 5]]


#### 12. Print the 4 corner pixels of the matrix

In [172]:
# Solution

print('\n matrix is :\n',m1)
print('\ntop left  corner pixel is :',m1[0,0])
print('\ntop right corner pixel is :',m1[0,4])
print('\nbottom right corner pixel is :',m1[4,0])
print('\nbottom left corner pixel is :',m1[4,4])


 matrix is :
 [[ 9 25 50 34 45]
 [ 3 34 34 65  2]
 [ 5  7  3 76  3]
 [ 7  8  6 54  6]
 [23 12  8  5  8]]

top left  corner pixel is : 9

top right corner pixel is : 45

bottom right corner pixel is : 23

bottom left corner pixel is : 8


#### 13. Create three matrix m1,m2,m3 with the elements grouped in the figure below
<img src = "np_mat2.png">

In [248]:
# Solution 
import numpy as np
print(ar8)

m1a=m1[:2,2:4]
print('\n Matrix M1 is :\n',m1a)
m1b=m1[3:5,0:2]
print('\n Matrix M2 is :\n',m1b)
m1c=m1[2:,2:]
print('\n Matrix M3 is :\n',m1c)


[[ 9 25 50 34 45]
 [ 3 34 34 65  2]
 [ 5  7  3 76  3]
 [ 7  8  6 54  6]
 [23 12  8  5  8]]

 Matrix M1 is :
 [[50 34]
 [34 65]]

 Matrix M2 is :
 [[ 7  8]
 [23 12]]

 Matrix M3 is :
 [[ 3 76  3]
 [ 6 54  6]
 [ 8  5  8]]


In [ ]:
# 14. Reshape all the three matrix segmented in the above task in to three  1-dimensional vector.

In [255]:
# Solution

m1a_f=m1a.flatten()
print('\n 1-dmin m1 is :\n',m1a_f)
m1b_f=m1b.flatten()
print('\n 1-dmin m2 is :\n',m1b_f)
m1c_f=m1c.flatten()
print('\n 1-dmin m3 is :\n',m1c_f)


 1-dmin m1 is :
 [[50 34 34 65]]

 1-dmin m2 is :
 [[ 7  8 23 12]]

 1-dmin m3 is :
 [[ 3 76  3  6 54  6  8  5  8]]


#### 15. Concatenate the matrix m1 and m2 in both vertical and horizontal direction

In [296]:
# Solution
print('\n 1-dmin m1 is :\n',m1a_f)
m1b_f=m1b.flatten()
print('\n 1-dmin m2 is :\n',m1b_f)
m1m2_v=np.concatenate((m1a_f,m1b_f))
print('m1 & m2 in vertical concatenation is :\n\n',m1m2_v)

m1m2_h=np.concatenate((m1a_f,m1b_f),axis=1)
print('\nm1 & m2 in horizontal concatenation is :\n\n',m1m2_h)



 1-dmin m1 is :
 [[50 34 34 65]]

 1-dmin m2 is :
 [[ 7  8 23 12]]
m1 & m2 in vertical concatenation is :

 [[50 34 34 65]
 [ 7  8 23 12]]

m1 & m2 in horizontal concatenation is :

 [[50 34 34 65  7  8 23 12]]


#### 16. Add, Subtract, multiply, divide the matrixes m1 and m2

In [273]:
# Solution
print('m1 is \n',m1a_f)
print('\nm2 is \n',m1b_f)
m1m2_add= np.array(m1a_f + m1b_f)
print('\nm1 + m2 is :\n',m1m2_add)



m1 is 
 [[50 34 34 65]]

m2 is 
 [[ 7  8 23 12]]

m1 + m2 is :
 [[57 42 57 77]]


#### 17. Add the m1 with m3 by removing the first row and last column of m3

In [288]:
# Solution
print('m3 matrix is :\n',m1c)
print('\nm1 matrix is :\n',m1a)
m3a= m1c[1:,:2]
print('\nm3 minus 1st row & last column is m3a:\n',m3a)



m1m3a_add = np.array(m1a+m3a)
print('\nm3a + m1 is :\n',m1m3a_add)



m3 matrix is :
 [[ 3 76  3]
 [ 6 54  6]
 [ 8  5  8]]

m1 matrix is :
 [[50 34]
 [34 65]]

m3 minus 1st row & last column is m3a:
 [[ 6 54]
 [ 8  5]]

m3a + m1 is :
 [[56 88]
 [42 70]]


#### 18. Form the matrix m4 by concatenating (as a new row) the vector [me1, me2] with the matrix m1, where me1 and me2 are the mean values of each column on m1.

In [310]:
# Solution
print('m1 is :\n',m1a)
m1a1_mean= m1a.mean(axis=0)
print('\n mean of m1 columns is :\n',m1a1_mean)

m4=np.vstack((m1a,m1a1_mean))
print('\nm4 with new column added to m1 is :\n',m4)


m1 is :
 [[50 34]
 [34 65]]

 mean of m1 columns is :
 [[42.  49.5]]

m4 with new column added to m1 is :
 [[50.  34. ]
 [34.  65. ]
 [42.  49.5]]


#### 19. Perform the matrix multiplication between m3 and m4

In [313]:
# Solution
print('m3 matrix is :\n',m1c)
print('\nm4 matrix is :\n',m4)
m1cm4_prod = np.array(m1c*m4)
print('\nm3 * m4 is : \n',m1cm4_prod)



m3 matrix is :
 [[ 3 76  3]
 [ 6 54  6]
 [ 8  5  8]]

m4 matrix is :
 [[50.  34. ]
 [34.  65. ]
 [42.  49.5]]

m1 * m4 is : 
 [[2860.  5190.5]
 [2388.  4011. ]
 [ 906.   993. ]]


#### 20. Compute the maximum and minimum value of mean, variance, standard deviation for each row of matrix created in question number 8.

In [330]:
# Solution
print ('matrix m1 created in qn.8 is :\n',m1)

m1_row_mean=np.mean(m1,axis=1)
print('\n mean of each row of m1 is :\n',m1_row_mean)

m1_row_var= np.var(m1,axis=1)
print('\n variance of each row of m1 is :\n',m1_row_var)

m1_row_std= np.std(m1,axis=1)
print('\n std deviation of each row of m1 is :\n',m1_row_std)

matrix m1 created in qn.8 is :
 [[ 9 25 50 34 45]
 [ 3 34 34 65  2]
 [ 5  7  3 76  3]
 [ 7  8  6 54  6]
 [23 12  8  5  8]]

 mean of each row of m1 is :
 [[32.6]
 [27.6]
 [18.8]
 [16.2]
 [11.2]]

 variance of each row of m1 is :
 [[214.64]
 [548.24]
 [820.16]
 [357.76]
 [ 39.76]]

 std deviation of each row of m1 is :
 [[14.65059726]
 [23.41452541]
 [28.63843571]
 [18.91454467]
 [ 6.30555311]]


#### 21. Compute the average and strike rate for each player and sort it decending way (seperately for avg and strike rate)
<img src = 'crick1.png'>

In [391]:
# Solution 
p=np.array(['MSD','KHO','ROH','RAH','DHA'])
print('\n Players are :\n',player)
r=np.array([54,60,10,65,102,2,78,32,3,110,1,92,56,6,12,42,12,8,22,11],dtype='i')
runs=r.reshape(5,4)
print('\n Runs matrix is :\n',runs)
b=np.array([50,42,22,78,95,8,65,43,9,100,7,101,27,3,11,31,24,20,36,27],dtype='i')
balls=b.reshape(5,4)
print('\n Balls matrix is :\n',balls)

a_rate= np.mean(runs,axis=1)
print('\n Runs Average of playes are : \n',a_rate)
a_rate_s=np.sort(a_rate)[::-1]
print('\n Average in "descending" order is :\n',a_rate_s)

avg_rate = np.concatenate((p,a_rate),axis=0)
#print(player_s_rate)
pl_avg=avg_rate.reshape(2,5)
#print(strike_rate)
#print('\n Runs Average of playes are : \n\n',pl_avg)
avg=pl_avg.T
#avg_s=avg.argsort() 
#print('\n Runs Average of playes are : \n\n',avg)

t_balls = np.sum(balls,axis=1)
t_runs  = np.sum(runs,axis=1)
print('\n Total runs per player  is : \n',t_runs)
print('\n Total balls per player is :\n',t_balls)

s_rate = np.array(t_runs/t_balls)
print('\nStrike rate of players are :\n',s_rate)

s_rate_s=np.sort(s_rate)[::-1]
print('\n Strike rate of players in "desceding" order is :\n',s_rate_s)


 Players are :
 ['MSD' 'KHO' 'ROH' 'RAH' 'DHA']

 Runs matrix is :
 [[ 54  60  10  65]
 [102   2  78  32]
 [  3 110   1  92]
 [ 56   6  12  42]
 [ 12   8  22  11]]

 Balls matrix is :
 [[ 50  42  22  78]
 [ 95   8  65  43]
 [  9 100   7 101]
 [ 27   3  11  31]
 [ 24  20  36  27]]

 Runs Average of playes are : 
 [47.25 53.5  51.5  29.   13.25]

 Average in "descending" order is :
 [53.5  51.5  47.25 29.   13.25]

 Total runs per player  is : 
 [189 214 206 116  53]

 Total balls per player is :
 [192 211 217  72 107]

Strike rate of players are :
 [0.984375   1.01421801 0.94930876 1.61111111 0.4953271 ]

 Strike rate of players in "desceding" order is :
 [1.61111111 1.01421801 0.984375   0.94930876 0.4953271 ]


#### 22. The students mark was recorded in a numpy array: marks = np.array([65,84,47,56,89,98,48,77,80,39]).  Cutoff for pass is 50 marks. Write the logic to print the number of students passed and failed. 

In [545]:
# Solution
marks = np.array([65,84,47,56,89,98,48,77,80,39])
print('\nList of marks is :\n',marks)

p=np.where(marks>=50)
pass_list = np.array(marks[p])
print('\nNum of students passed is :',pass_list.size)
           
f=np.where(marks<50)
fail_list = np.array(marks[f])
print('\nNum of students failed is:',fail_list.size)



List of marks is :
 [65 84 47 56 89 98 48 77 80 39]

Num of students passed is : 7

Num of students failed is: 3


#### 23. The class incharge decided to give a mercy mark of 5 for those who scored between 45 and 49. Also the bonus of 5 marks awarded to the students who scored more than 80. Print all the student marks and compute the increase in the pass percentage of class. Any score more than 100 must be recorded as only 100.

In [556]:
# Solution

marks = np.array([65,84,47,56,89,98,48,77,80,39])
marks_initial = np.copy(marks)
print('\ninitial list is :\n',marks)

#grace mark calculation
grace_list = np.where(np.logical_and(marks>=45,marks<=49))

for i in grace_list:
    marks[i]= marks[i]+5

#bonus calculation
bonus_list = list(np.where(marks>80))[0]
for k in bonus_list:
        marks[k]= marks[k] + 5
        if marks[k] > 100:
            marks[k] = 100

print('\n Final list with grace and bonus applied is \n',marks)

#pass percentatge calculation

o_pass= marks[np.where(marks_initial>=50)]
old_tot=o_pass.size
print('\nold pass total is :',old_tot)

n_pass= marks[np.where(marks>=50)]
new_tot=n_pass.size
print('\nnew pass total is :',new_tot)

#pass_perc = ((new_tot - old_tot)/old_tot)*100
print('\nclass pass percentage is:',((new_tot - old_tot)/old_tot)*100)



initial list is :
 [65 84 47 56 89 98 48 77 80 39]

 Final list with grace and bonus applied is 
 [ 65  89  52  56  94 100  53  77  80  39]

old pass total is : 7

new pass total is : 9

class pass percentage is: 28.57142857142857


#### 24. Print the time taken for performing the following operation using list and numpy array
####       (x(i)^2 +8) / y(i),   where x and y are real integers from 1 to 60000

In [619]:
# Solution


import numpy as np
import time


lx= list(range(1,60000))
ly= list(range(1,60000))

start_l_time = time.time()
lz=[(x**2+8/y) for x ,y in zip(lx,ly)]
#print(lz)
total_l_time = time.time()-start_l_time
print('\nList processing time is :', total_l_time)

start_a_time = time.time()
ax= np.array(range(1,60000))
ay= np.array(range(1,60000))
az= ax**2+8/ay
#print(az)
total_a_time=time.time()-start_a_time
print('\narray processing time is:',total_a_time)



List processing time is : 0.05405306816101074

array processing time is: 0.014639854431152344


#### 25. Create a Github account and upload your solution with the short write-up on Numpy

In [ ]:
# Solution

https://github.com/ggeorge6/NumPy

